### PR TITLE
add continuous variables

### PR DESCRIPTION
**Pull request by AmethystGear**
Adding continuous variables to boba. Continuous variables can be specified by adding a json object to the "options" list in this format: 
```
{
    "sampling_method" : "lognormal",
    "sample_size" : 3,
    "std_dev" : 1,
    "mean" : 2
}
```
There are currently 3 sampling methods supported, `uniform`, `normal`, and `lognormal`, as defined by this dictionary here:
```
        sampling_methods = {
            'uniform': (['min', 'max'], random.uniform), 
            'lognormal': (['mean', 'std_dev'], random.lognormvariate), 
            'normal' : (['mean', 'std_dev'], random.normalvariate)
        }
```
more methods can be easily added by modifying this dictionary in the code.
`lognormal` and `normal` sampling methods accept `mean` and `std_dev` as parameters, while `uniform` accepts `min` and `max` as parameters.

Continuous variables can be put alongside static variables like so:
```
"options" : [
{
    "sampling_method" : "lognormal",
    "sample_size" : 3,
    "std_dev" : 1,
    "mean" : 2
},
2,
10,
8
]
```
and they can also be put inside list objects as the algorithm that expands these json objects into discrete samples recursively searches through lists to find any json objects in these formats.

### CODE REVIEW

**Comment by yyyliu** [comment]
I like how you made it easy to add supported methods! 

I think a variable can only be either continuous or discrete, but it seems at the moment a variable can have both continuous and discrete values. Could you change this design? If I remembered correctly, we have a `type` field with `discrete` as the default value. So for a continuous variable, its `type` field will be `continuous`, and it can have all the other fields you listed above.

Could you add some test cases to cover a few common scenarios? You could add the tests in this [file](https://github.com/uwdata/multiverse-spec/blob/master/test/test_decision_parser.py); if you want to test end-to-end scenarios, you can add them [here](https://github.com/uwdata/multiverse-spec/blob/master/test/test_parser.py).

It might also be helpful to go over other methods in the [Decision Parser class](https://github.com/uwdata/multiverse-spec/blob/master/boba/decisionparser.py) to make sure they support continuous variables, because they were previously designed to support discrete variables only. (At the very least, it seems some method documentation needs an update :)

We might want to add a `seed` field, which allows users to specify a random seed for deterministic output across multiple runs.

Is `min`, `max`, `std_dev` or `mean` optional? If so, what are the default values? If not, we might want to throw an informative error. 

Lastly, after we've decided on the syntax, could you update the documentation [here](https://github.com/uwdata/multiverse-spec/blob/master/tutorial/rules.md)?

**Comment by AmethystGear** [comment]
just a few notes:

1. I didn't see a 'type' field anywhere for variables, (and I'm not sure if we should implement one - I'll discuss that later below.)
2. Definitely will add an optional seed parameter so that we can have repeatable runs.
3. Any parameters defined in the dictionary are not optional. I will add an error that will be thrown if one of these required variables is undefined.
4. Currently, there is no concept of a 'continuous variable' really. When the I see this:
```
"options" : [
{
    "sampling_method" : "uniform",
    "sample_size" : 3,
    "min" : 1,
    "max" : 2
}
]
```
I really just end up converting it to something like this when reading the boba config (values are arbitrary):
```
"options" : [ 1.1738703, 1.77334, 1.045543]
```
and then we just treat it as a discrete variable. So all the functions will still work, because they will operate on these discrete values instead of on a new variable type.
5. Since 'continuous variables' are really just shortcuts for expanding into discrete random values, should we allow them to be mixed with specific cases? In my opinion, this is good because it allows me to add a specific case that i am interested in knowing the outcome of, but also allows me to test a bunch of other cases in the interval. But if we do not want this, we can pretty easily remove it by throwing an error when a user tries to mix static values and continuous values.
6. I'll add a few test cases.
7. Yep, i'll add documentation once we figure out the syntax that we want for these variables.

**Comment by yyyliu** [comment]
Thanks for explaining your rationale! Now I understand why you mixed sampling with discrete values. The scenario of specific cases makes sense, but perhaps we could add a field `must_have` (we need a better name) and any values specified there will be added alongside the random samples.

Though implementation-wise, a continuous variable will be turned into discrete values so it is the same as a discrete variable, they are conceptually different ... As we'll probably treat continuous variables differently when we apply optimization, it is better to separate these two types now. The only reason to keep them mixed is when the variable itself take different forms at different intervals, for example:

> If x > 0, x can be any value between 1 and 2
> If x <=0, x can be one of {0, -1, -2}

But I think this is very rare. We might ask other collaborators for their opinion over slack (I'll create a slack group tomorrow night).

**Comment by AmethystGear** [comment]
Based on the feedback, I have improved the syntax and implementation of continuous variables. Additionally, there is a new simple example, `simple_cont`, which provides an example of how a continuous variable works.

again, there are 3 supported sampling methods, as defined here. Each method maps to an object that contains the sampling function, then the required variables, and finally the optional variables. If any of the required variables are missing for a particular continuous variable, an error is thrown.
```
discretization_methods = {
    'uniform': DiscretizationFn(DecisionParser.random_uniform, ['min', 'max'], ['exclusive']), 
    'lognormal': DiscretizationFn(DecisionParser.random_lognormal, [], ['mean', 'std_dev', 'exclusive', 'range']), 
    'normal' : DiscretizationFn(DecisionParser.random_normal, [], ['mean', 'std_dev', 'exclusive', 'range'])
}
```
all optional variables have defaults. They are listed below:
```
exclusive = False
mean = 0
std_dev = 1
range = None
```
As was discussed in the feedback, we are still allowed to mix discrete and continuous options to ensure certain values are tested, and we are still allowed to have multiple continuous variables inside the options array.
Additionally, there are now two decision maps inside the `DecisionParser` class, `decisions` and `discrete_decisions`. `discrete_decisions` contains all the decision points, but all continuous variables are discretized. `decisions` simply contains all the decision points, without discretization. Some functions in the `DecisionParser` class were modified to return values based on the `discrete_decisions` map instead of the `decisions` map.

Currently, there is no support for inline continuous variables. I was not sure if we should add these or not.

**Comment by AmethystGear** [comment]
ok! unit tests are added. I added two new `.json` files to `spec/`: `continuous.json` and `continuous-err.json`. `continuous.json` contains test cases A-L which test various continuous variable expansions for different distributions. `continuous-err.json` contains test cases 0-14 which pass bad continuous variable input to the decisionparser, and then expect certain exceptions to be thrown.

new test cases can be added easily by first adding to either `continuous.json` or `continuous-err.json`, and then adding the expected result of the test to the correct dictionary in `test_decision_parser.py`. (in test_continuous_vars we have `expected_values` for tests where a result is expected, and in `test_continuous_err` we have `expected_errs` for tests where an error is expected.)

**Comment by yyyliu** [comment]
The unit tests are looking great! I did a squash and merge to get rid of some intermediate commits that did not pass the test. You might selectively squash on your end though (in the future), so milestone commits in the commit history are still preserved.

**Pull request merged**
